// Procedural textures for the Lunar Module exterior (no assets, all generated at load time).
//
// Tileable material maps (foil / quilt / panel) are generated by texgen.js in a Web Worker so the
// main thread never blocks: the functions below return THREE.DataTextures immediately (neutral
// placeholder data) and fill them in when the worker answers. In node (no Worker) they are
// generated synchronously. `texturesReady()` resolves when every requested map is filled.
//
// Text decals ("UNITED STATES" + flag panel, the Apollo 11 plaque, placards) use a 2D canvas when a
// DOM exists (null otherwise). Results are cached per size/seed.

import * as THREE from 'three';
import { rng, generate } from './texgen.js';

export { rng };

const cache = new Map();
const clonesOf = new Map(); // base texture -> clones (repeat/rotation variants sharing its Source)

/**
 * Clone a procedural texture (shares the image Source) and keep track of the clone so it is
 * re-uploaded when the generated data arrives.
 * @param {THREE.Texture} tex
 * @returns {THREE.Texture}
 */
export function cloneTex(tex) {
  const c = tex.clone();
  if (!clonesOf.has(tex)) clonesOf.set(tex, []);
  clonesOf.get(tex).push(c);
  return c;
}

function cached(key, fn) {
  if (!cache.has(key)) cache.set(key, fn());
  return cache.get(key);
}

function dataTex(data, size, { srgb = false } = {}) {
  const t = new THREE.DataTexture(data, size, size, THREE.RGBAFormat, THREE.UnsignedByteType);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.magFilter = THREE.LinearFilter;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  t.generateMipmaps = true;
  t.anisotropy = 8;
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  t.needsUpdate = true;
  return t;
}

/** Filled placeholder: RGBA constant. */
function solid(size, r, g, b, a = 255) {
  const d = new Uint8Array(size * size * 4);
  for (let i = 0; i < d.length; i += 4) {
    d[i] = r;
    d[i + 1] = g;
    d[i + 2] = b;
    d[i + 3] = a;
  }
  return d;
}

// ------------------------------------------------------------------ async generation

let worker = null;
let workerFailed = false;
let jobId = 0;
const jobs = new Map();
let pending = 0;
let readyResolvers = [];

function finishJob() {
  pending--;
  if (pending === 0) {
    const rs = readyResolvers;
    readyResolvers = [];
    rs.forEach((r) => r());
  }
}

/** Promise resolved when every requested procedural map has been generated and uploaded. */
export function texturesReady() {
  if (pending === 0) return Promise.resolve();
  return new Promise((r) => readyResolvers.push(r));
}

/** Copy generated arrays into the textures (and their clones) and flag them for upload. */
function fill(texs, res) {
  for (const [name, t] of Object.entries(texs)) {
    if (!res[name]) continue;
    t.image.data.set(res[name]);
    t.needsUpdate = true;
    for (const c of clonesOf.get(t) || []) c.needsUpdate = true;
  }
}

function getWorker() {
  if (worker || workerFailed) return worker;
  if (typeof Worker === 'undefined' || typeof window === 'undefined') {
    workerFailed = true;
    return null;
  }
  // Vite inline worker (single-file build friendly); created asynchronously
  worker = import('./texgen.worker.js?worker&inline')
    .then((mod) => {
      const w = new mod.default();
      w.onmessage = (e) => {
        const job = jobs.get(e.data.id);
        if (!job) return;
        jobs.delete(e.data.id);
        fill(job.texs, e.data.res);
        finishJob();
      };
      w.onerror = (e) => {
        console.warn('LM texture worker failed, generating on the main thread', e.message || e);
        for (const [id, job] of jobs) {
          jobs.delete(id);
          fill(job.texs, generate(job.kind, job.size, job.seed));
          finishJob();
        }
      };
      return w;
    })
    .catch((err) => {
      console.warn('LM texture worker unavailable, generating on the main thread', err);
      workerFailed = true;
      return null;
    });
  return worker;
}

function schedule(kind, size, seed, texs) {
  pending++;
  const wp = getWorker();
  if (!wp) {
    fill(texs, generate(kind, size, seed));
    finishJob();
    return;
  }
  const id = ++jobId;
  jobs.set(id, { kind, size, seed, texs });
  wp.then((w) => {
    if (w) w.postMessage({ id, kind, size, seed });
    else if (jobs.has(id)) {
      jobs.delete(id);
      // main-thread fallback, spread over frames
      setTimeout(() => {
        fill(texs, generate(kind, size, seed));
        finishJob();
      }, 0);
    }
  });
}

// ------------------------------------------------------------------ public texture sets

/**
 * Crinkled foil set { normal, rough, tint } (tileable; one tile ~ 1 m of blanket).
 * @param {number} size texture size (power of two)
 * @param {number} seed variation seed
 */
export function foilTextures(size = 1024, seed = 7) {
  return cached(`foil${size}_${seed}`, () => {
    const texs = {
      normal: dataTex(solid(size, 128, 128, 255), size),
      rough: dataTex(solid(size, 0, 70, 255), size),
      tint: dataTex(solid(size, 230, 230, 230), size, { srgb: true }),
    };
    schedule('foil', size, seed, texs);
    return texs;
  });
}

/** Quilted blanket set { normal, rough }. */
export function quiltTextures(size = 512, seed = 11) {
  return cached(`quilt${size}_${seed}`, () => {
    const texs = { normal: dataTex(solid(size, 128, 128, 255), size), rough: dataTex(solid(size, 0, 140, 255), size) };
    schedule('quilt', size, seed, texs);
    return texs;
  });
}

/** Riveted panel set { normal, rough, tint } (one tile ~ 2 m of skin). */
export function panelTextures(size = 1024, seed = 23) {
  return cached(`panel${size}_${seed}`, () => {
    const texs = {
      normal: dataTex(solid(size, 128, 128, 255), size),
      rough: dataTex(solid(size, 0, 120, 255), size),
      tint: dataTex(solid(size, 225, 225, 225), size, { srgb: true }),
    };
    schedule('panel', size, seed, texs);
    return texs;
  });
}

// ------------------------------------------------------------------ canvas decals

function canvas2d(w, h) {
  if (typeof document === 'undefined') return null;
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

function canvasTex(c, srgb = true) {
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  t.anisotropy = 8;
  t.generateMipmaps = true;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  return t;
}

/** US flag drawn into a 2D context (proportions per Executive Order 10834). */
function drawFlag(g, x, y, w) {
  const h = w / 1.9;
  const stripe = h / 13;
  for (let i = 0; i < 13; i++) {
    g.fillStyle = i % 2 ? '#f4f1ea' : '#b22234';
    g.fillRect(x, y + i * stripe, w, stripe + 0.5);
  }
  const cw = w * 0.4;
  const ch = stripe * 7;
  g.fillStyle = '#3c3b6e';
  g.fillRect(x, y, cw, ch);
  g.fillStyle = '#f4f1ea';
  const sr = ch * 0.0616 / 0.76 * 0.75;
  for (let row = 0; row < 9; row++) {
    const n = row % 2 ? 5 : 6;
    for (let k = 0; k < n; k++) {
      const sx = x + cw * ((row % 2 ? 2 : 1) + k * 2) / 12;
      const sy = y + ch * (row + 1) / 10;
      g.beginPath();
      for (let p = 0; p < 10; p++) {
        const a = -Math.PI / 2 + p * Math.PI / 5;
        const rr = p % 2 ? sr * 0.38 : sr;
        g.lineTo(sx + Math.cos(a) * rr, sy + Math.sin(a) * rr);
      }
      g.fill();
    }
  }
  return h;
}

/**
 * Descent-stage identification panel: US flag above black "UNITED STATES" lettering on a
 * light panel. Returns a texture (aspect 1:1.25, portrait) or null without a DOM.
 */
export function flagPanelTexture() {
  return cached('flagpanel', () => {
    const c = canvas2d(512, 640);
    if (!c) return null;
    const g = c.getContext('2d');
    // light, slightly weathered painted panel
    const grd = g.createLinearGradient(0, 0, 0, 640);
    grd.addColorStop(0, '#d9d6cf');
    grd.addColorStop(1, '#c9c5bc');
    g.fillStyle = grd;
    g.fillRect(0, 0, 512, 640);
    const r = rng(5);
    for (let i = 0; i < 1600; i++) {
      g.fillStyle = `rgba(${r() < 0.5 ? '0,0,0' : '255,255,255'},${0.03 * r()})`;
      g.fillRect(r() * 512, r() * 640, 2 + r() * 20, 1 + r() * 3);
    }
    drawFlag(g, 86, 70, 340);
    g.fillStyle = '#111';
    g.textAlign = 'center';
    g.textBaseline = 'middle';
    g.font = 'bold 82px "Helvetica Neue", Helvetica, Arial, sans-serif';
    g.fillText('UNITED', 256, 360);
    g.fillText('STATES', 256, 460);
    // edge shading
    g.strokeStyle = 'rgba(0,0,0,0.35)';
    g.lineWidth = 6;
    g.strokeRect(3, 3, 506, 634);
    return canvasTex(c);
  });
}

/** The Apollo 11 plaque (stainless steel, engraved) as a colour texture, or null. */
export function plaqueTexture() {
  return cached('plaque', () => {
    const c = canvas2d(768, 512);
    if (!c) return null;
    const g = c.getContext('2d');
    const r = rng(9);
    // brushed stainless
    g.fillStyle = '#b9bcbf';
    g.fillRect(0, 0, 768, 512);
    for (let i = 0; i < 2600; i++) {
      const y = r() * 512;
      g.strokeStyle = `rgba(${r() < 0.5 ? '255,255,255' : '40,40,40'},${0.05 + 0.05 * r()})`;
      g.beginPath();
      const x = r() * 768;
      g.moveTo(x, y);
      g.lineTo(x + 40 + r() * 200, y);
      g.stroke();
    }
    g.strokeStyle = '#2a2a2a';
    g.lineWidth = 3;
    g.strokeRect(14, 14, 740, 484);
    // two hemispheres
    const hemi = (cx) => {
      g.beginPath();
      g.arc(cx, 150, 88, 0, Math.PI * 2);
      g.stroke();
      g.lineWidth = 1.5;
      for (let k = -2; k <= 2; k++) {
        g.beginPath();
        g.ellipse(cx, 150, 88 * Math.cos(k * 0.5), 88, 0, 0, Math.PI * 2);
        g.stroke();
        g.beginPath();
        g.moveTo(cx - 88 * Math.cos(k * 0.5), 150 + k * 33);
        g.lineTo(cx + 88 * Math.cos(k * 0.5), 150 + k * 33);
        g.stroke();
      }
      // crude continents
      g.fillStyle = 'rgba(30,30,30,0.55)';
      for (let i = 0; i < 9; i++) {
        g.beginPath();
        g.ellipse(cx - 50 + r() * 100, 90 + r() * 120, 8 + r() * 26, 10 + r() * 30, r() * 3, 0, Math.PI * 2);
        g.fill();
      }
      g.lineWidth = 3;
    };
    hemi(250);
    hemi(518);
    g.fillStyle = '#1b1b1b';
    g.textAlign = 'center';
    g.font = 'bold 30px Georgia, "Times New Roman", serif';
    g.fillText('HERE MEN FROM THE PLANET EARTH', 384, 290);
    g.fillText('FIRST SET FOOT UPON THE MOON', 384, 326);
    g.fillText('JULY 1969, A.D.', 384, 362);
    g.fillText('WE CAME IN PEACE FOR ALL MANKIND', 384, 398);
    g.font = 'italic 20px Georgia, serif';
    const sig = ['Neil A. Armstrong', 'Michael Collins', 'Edwin E. Aldrin, Jr.', 'Richard Nixon'];
    sig.forEach((s, i) => g.fillText(s, 120 + i * 176, 450));
    g.font = '11px Arial';
    ['ASTRONAUT', 'ASTRONAUT', 'ASTRONAUT', 'PRESIDENT, UNITED STATES OF AMERICA'].forEach((s, i) => g.fillText(s, 120 + i * 176, 472));
    return canvasTex(c);
  });
}

/**
 * Small placard / marking texture atlas for the ascent stage (docking target cross, hatch
 * markings, quad labels). Returns { tex, rects } or null. rects[name] = [u0,v0,u1,v1].
 */
export function markingsTexture() {
  return cached('markings', () => {
    const c = canvas2d(512, 512);
    if (!c) return null;
    const g = c.getContext('2d');
    g.fillStyle = '#000';
    g.fillRect(0, 0, 512, 512);
    const rects = {};
    // docking target: black disc, white standoff cross & tick circle (0..256, 0..256)
    g.fillStyle = '#0b0b0b';
    g.fillRect(0, 0, 256, 256);
    g.strokeStyle = '#f2f2ee';
    g.lineWidth = 10;
    g.beginPath();
    g.arc(128, 128, 110, 0, Math.PI * 2);
    g.stroke();
    g.lineWidth = 5;
    g.beginPath();
    g.arc(128, 128, 60, 0, Math.PI * 2);
    g.stroke();
    for (let k = 0; k < 12; k++) {
      const a = k * Math.PI / 6;
      g.beginPath();
      g.moveTo(128 + Math.cos(a) * 92, 128 + Math.sin(a) * 92);
      g.lineTo(128 + Math.cos(a) * 110, 128 + Math.sin(a) * 110);
      g.stroke();
    }
    rects.target = [0, 0.5, 0.5, 1];
    // hatch placard "HATCH / PULL" + arrows (256..512, 0..256)
    g.fillStyle = '#1a1a1a';
    g.fillRect(256, 0, 256, 256);
    g.fillStyle = '#e8e4d8';
    g.font = 'bold 30px Arial';
    g.textAlign = 'center';
    g.fillText('HATCH', 384, 70);
    g.font = 'bold 22px Arial';
    g.fillText('PULL TO OPEN', 384, 110);
    g.fillText('EXT HANDLE', 384, 150);
    g.beginPath();
    g.moveTo(344, 190);
    g.lineTo(424, 190);
    g.lineTo(424, 175);
    g.lineTo(454, 200);
    g.lineTo(424, 225);
    g.lineTo(424, 210);
    g.lineTo(344, 210);
    g.fill();
    rects.hatch = [0.5, 0.5, 1, 1];
    // RCS quad warning stripe (0..256, 256..512)
    for (let i = 0; i < 8; i++) {
      g.fillStyle = i % 2 ? '#101010' : '#c9b037';
      g.beginPath();
      g.moveTo(i * 40 - 40, 512);
      g.lineTo(i * 40, 512);
      g.lineTo(i * 40 + 40, 256);
      g.lineTo(i * 40, 256);
      g.fill();
    }
    rects.stripe = [0, 0, 0.5, 0.5];
    // white paint (256..512, 256..512) — generic light marking
    g.fillStyle = '#e9e6de';
    g.fillRect(256, 256, 256, 256);
    rects.white = [0.5, 0, 1, 0.5];
    const t = canvasTex(c);
    return { tex: t, rects };
  });
}
