// Texture management for the CSM exterior.
//
// * Skin atlases (CM foil, SM skin) are generated by texgen.js in an inline Web Worker so the main
//   thread never stalls; `skinAtlas()` returns three DataTextures immediately (neutral placeholder
//   data) and fills them in when the worker answers. Without Worker support (node) they are
//   generated synchronously.
// * Small canvas textures (the "UNITED STATES" + flag decal, the SPS nozzle banding, the SM aft
//   bulkhead) are drawn on a 2D canvas in the main thread (a few ms). They return null without a DOM.

import * as THREE from 'three';
import { generate } from './texgen.js';
import TexWorker from './texgen.worker.js?worker&inline';

const pending = [];
let worker = null;
let nextId = 1;
const callbacks = new Map();

function getWorker() {
  if (worker !== null) return worker;
  try {
    worker = typeof Worker !== 'undefined' ? new TexWorker() : false;
    if (worker) {
      worker.onmessage = (e) => {
        const cb = callbacks.get(e.data.id);
        callbacks.delete(e.data.id);
        cb?.(e.data);
      };
      worker.onerror = (e) => {
        console.warn('CSM texture worker failed, generating on the main thread', e.message || e);
        const list = [...callbacks.values()];
        callbacks.clear();
        worker = false;
        for (const cb of list) cb({ fallback: true });
      };
    }
  } catch (e) {
    worker = false;
  }
  return worker;
}

function dataTex(data, w, h, { srgb = false, wrapS = THREE.RepeatWrapping } = {}) {
  const t = new THREE.DataTexture(data, w, h, THREE.RGBAFormat, THREE.UnsignedByteType);
  t.wrapS = wrapS;
  t.wrapT = THREE.ClampToEdgeWrapping;
  t.magFilter = THREE.LinearFilter;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  t.generateMipmaps = true;
  t.anisotropy = 8;
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  t.flipY = false;
  t.needsUpdate = true;
  return t;
}

function solid(w, h, r, g, b, a = 255) {
  const d = new Uint8Array(w * h * 4);
  for (let i = 0; i < d.length; i += 4) {
    d[i] = r;
    d[i + 1] = g;
    d[i + 2] = b;
    d[i + 3] = a;
  }
  return d;
}

/**
 * Procedural skin atlas.
 * @param {'cmFoil'|'smSkin'} kind
 * @param {object} opts generator options (width, height, ...)
 * @param {{albedo:number[], orm:number[]}} placeholder RGBA bytes used until the data arrives
 * @returns {{map: THREE.DataTexture, orm: THREE.DataTexture, normal: THREE.DataTexture, ready: Promise<void>}}
 */
export function skinAtlas(kind, opts, placeholder) {
  // placeholders are tiny (4x4) so that nothing big is uploaded twice
  const pw = 4;
  const ph = 4;
  const map = dataTex(solid(pw, ph, ...placeholder.albedo), pw, ph, { srgb: true });
  const orm = dataTex(solid(pw, ph, ...placeholder.orm), pw, ph);
  const normal = dataTex(solid(pw, ph, 128, 128, 255), pw, ph);
  const apply = (res) => {
    const W = res.width;
    const H = res.height;
    for (const [tex, arr] of [[map, res.albedo], [orm, res.orm], [normal, res.normal]]) {
      tex.image = { data: arr, width: W, height: H };
      tex.dispose(); // size changed: force re-allocation of the GPU texture
      tex.needsUpdate = true;
    }
  };
  const ready = new Promise((resolve) => {
    const w = getWorker();
    const local = () => {
      apply(generate(kind, opts));
      resolve();
    };
    if (!w) {
      local();
      return;
    }
    const id = nextId++;
    callbacks.set(id, (msg) => {
      if (msg.fallback || msg.error) {
        if (msg.error) console.warn('CSM texture worker error:', msg.error);
        local();
        return;
      }
      apply(msg.res);
      resolve();
    });
    w.postMessage({ id, kind, opts });
  });
  pending.push(ready);
  return { map, orm, normal, ready };
}

/** Resolves when every requested skin atlas is filled. */
export function texturesReady() {
  return Promise.all(pending).then(() => undefined);
}

function canvas(w, h) {
  if (typeof document === 'undefined') return null;
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

function canvasTex(c, { srgb = true, repeat = false } = {}) {
  const t = new THREE.CanvasTexture(c);
  t.flipY = false;
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  t.anisotropy = 8;
  t.wrapS = t.wrapT = repeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
  t.needsUpdate = true;
  return t;
}

/**
 * "UNITED STATES" (stacked letters, read nose-up) with the US flag forward of it, as painted on the
 * SM. Canvas X runs with increasing azimuth (the viewer's right when looking at the SM nose-up),
 * canvas Y runs aft. Transparent background.
 * @param {number} widthM decal width (m)
 * @param {number} heightM decal height (m)
 * @returns {THREE.CanvasTexture|null}
 */
export function flagDecalTexture(widthM, heightM) {
  const W = 256;
  const H = Math.round((W * heightM) / widthM / 4) * 4;
  const c = canvas(W, H);
  if (!c) return null;
  const g = c.getContext('2d');
  const pxm = W / widthM;
  g.clearRect(0, 0, W, H);

  // --- flag (0.50 x 0.263 m, stripes horizontal with the vehicle nose up)
  const fw = 0.46 * pxm;
  const fh = fw / 1.9;
  const fx = (W - fw) / 2;
  const fy = 0.04 * pxm;
  const stripe = fh / 13;
  for (let k = 0; k < 13; k++) {
    g.fillStyle = k % 2 === 0 ? '#b3202e' : '#f4f1ea';
    g.fillRect(fx, fy + k * stripe, fw, stripe + 0.5);
  }
  const cw = fw * 0.4;
  const ch = stripe * 7;
  g.fillStyle = '#243a73';
  g.fillRect(fx, fy, cw, ch);
  g.fillStyle = '#f4f1ea';
  const sr = ch * 0.032;
  for (let row = 0; row < 9; row++) {
    const n = row % 2 === 0 ? 6 : 5;
    for (let k = 0; k < n; k++) {
      const x = fx + cw * ((row % 2 === 0 ? 1 : 2) + k * 2) / 12;
      const y = fy + ch * (row + 1) / 10;
      star(g, x, y, sr);
    }
  }
  // --- lettering: 12 letters stacked, reading nose (top) to tail
  const text = 'UNITEDSTATES';
  const top = fy + fh + 0.16 * pxm;
  const avail = H - top - 0.04 * pxm;
  const gap = 0.12 * pxm; // word space between UNITED and STATES
  const cell = (avail - gap) / 12;
  g.fillStyle = '#0b0b0b';
  g.textAlign = 'center';
  g.textBaseline = 'middle';
  const fontPx = Math.round(cell * 0.86);
  g.font = `bold ${fontPx}px "Helvetica Neue", Helvetica, Arial, "Liberation Sans", "DejaVu Sans", sans-serif`;
  for (let k = 0; k < text.length; k++) {
    const y = top + cell * (k + 0.5) + (k >= 6 ? gap : 0);
    g.save();
    g.translate(W / 2, y);
    g.scale(1.05, 1);
    g.fillText(text[k], 0, 0);
    g.restore();
  }
  return canvasTex(c);
}

// linear -> display byte (gamma 2.2) lookup
const GAMMA_LUT = (() => {
  const t = new Uint8Array(1025);
  for (let k = 0; k <= 1024; k++) t[k] = Math.round(Math.pow(k / 1024, 1 / 2.2) * 255);
  return t;
})();
const gammaByte = (c) => GAMMA_LUT[c <= 0 ? 0 : c >= 1 ? 1024 : (c * 1024) | 0];

function star(g, x, y, r) {
  g.beginPath();
  for (let k = 0; k < 10; k++) {
    const a = -Math.PI / 2 + (k * Math.PI) / 5;
    const rr = k % 2 === 0 ? r : r * 0.4;
    g.lineTo(x + Math.cos(a) * rr, y + Math.sin(a) * rr);
  }
  g.closePath();
  g.fill();
}

/**
 * SPS nozzle-extension banding along the nozzle (V = 0 at the attach flange, 1 at the exit): the
 * upper columbium section (disilicide coating, dark blue-grey), the lower titanium section (light
 * grey / pale tan), stiffener bands and faint heat streaks. Also returns a matching roughness map.
 * @returns {{map: THREE.CanvasTexture, rough: THREE.CanvasTexture, emissive: THREE.CanvasTexture}|null}
 */
export function spsNozzleTextures(vSplit = 0.3) {
  const W = 256;
  const H = 512;
  const c = canvas(W, H);
  const r = canvas(W, H);
  if (!c) return null;
  const g = c.getContext('2d');
  const gr = r.getContext('2d');
  const img = g.createImageData(W, H);
  const rim = gr.createImageData(W, H);
  let s = 12345;
  const rnd = () => ((s = (s * 16807) % 2147483647) / 2147483647);
  const colStreak = new Float32Array(W);
  for (let i = 0; i < W; i++) colStreak[i] = (rnd() - 0.5) * 0.06;
  for (let k = 0; k < 3; k++) for (let i = 0; i < W; i++) colStreak[i] = (colStreak[i] + colStreak[(i + 1) % W] + colStreak[(i + W - 1) % W]) / 3;
  for (let j = 0; j < H; j++) {
    const v = (j + 0.5) / H;
    const upper = v < vSplit;
    for (let i = 0; i < W; i++) {
      const o = (j * W + i) * 4;
      let R;
      let G;
      let B;
      let rough;
      if (upper) {
        // columbium with silicide coating: dark grey with a slight blue-violet cast
        const t = v / vSplit;
        R = 0.07 + t * 0.03;
        G = 0.075 + t * 0.03;
        B = 0.095 + t * 0.03;
        rough = 0.38;
      } else {
        // titanium extension: light grey, pale tan toward the exit
        const t = (v - vSplit) / (1 - vSplit);
        R = 0.62 + t * 0.06;
        G = 0.6 + t * 0.03;
        B = 0.54 - t * 0.03;
        rough = 0.5;
      }
      const n = colStreak[i] + (rnd() - 0.5) * 0.02;
      R += n;
      G += n;
      B += n;
      // stiffener / joint bands
      const bands = [vSplit, 0.62, 0.84];
      for (const bv of bands) {
        const d = Math.abs(v - bv) * H;
        if (d < 3) {
          const k = 1 - d / 3;
          R = R * (1 - k) + 0.55 * k;
          G = G * (1 - k) + 0.54 * k;
          B = B * (1 - k) + 0.52 * k;
          rough = rough * (1 - k) + 0.3 * k;
        }
      }
      // exit lip darkening
      if (v > 0.985) {
        R *= 0.7;
        G *= 0.7;
        B *= 0.7;
      }
      img.data[o] = gammaByte(R);
      img.data[o + 1] = gammaByte(G);
      img.data[o + 2] = gammaByte(B);
      img.data[o + 3] = 255;
      const rr = Math.min(255, Math.max(0, (rough + n) * 255));
      rim.data[o] = 255;
      rim.data[o + 1] = rr;
      rim.data[o + 2] = 255;
      rim.data[o + 3] = 255;
    }
  }
  g.putImageData(img, 0, 0);
  gr.putImageData(rim, 0, 0);
  const map = canvasTex(c);
  map.wrapS = THREE.RepeatWrapping;
  const rough = canvasTex(r, { srgb: false });
  rough.wrapS = THREE.RepeatWrapping;
  // heat glow: hottest at the attach flange, fading through the columbium section, faint on titanium
  const ec = canvas(4, 256);
  const eg = ec.getContext('2d');
  const grad = eg.createLinearGradient(0, 0, 0, 256);
  grad.addColorStop(0, '#ffffff');
  grad.addColorStop(vSplit * 0.6, '#b0b0b0');
  grad.addColorStop(vSplit, '#505050');
  grad.addColorStop(Math.min(1, vSplit + 0.12), '#141414');
  grad.addColorStop(1, '#000000');
  eg.fillStyle = grad;
  eg.fillRect(0, 0, 4, 256);
  const emissive = canvasTex(ec);
  return { map, rough, emissive };
}

/**
 * SM aft bulkhead heat shield (planar UV over a 4 x 4 m square centred on the axis): quilted
 * insulation gores, a stiffening ring, bolt circles and the engine opening.
 * @returns {{map: THREE.CanvasTexture, bump: THREE.CanvasTexture}|null}
 */
export function aftBulkheadTextures() {
  const S = 1024;
  const c = canvas(S, S);
  const b = canvas(S, S);
  if (!c) return null;
  const g = c.getContext('2d');
  const gb = b.getContext('2d');
  const pxm = S / 4;
  const cx = S / 2;
  g.fillStyle = '#8f9092';
  g.fillRect(0, 0, S, S);
  gb.fillStyle = '#808080';
  gb.fillRect(0, 0, S, S);
  // radial quilting gores
  const gores = 24;
  for (let k = 0; k < gores; k++) {
    const a0 = (k / gores) * Math.PI * 2;
    const a1 = ((k + 1) / gores) * Math.PI * 2;
    const shade = 130 + ((k * 37) % 5) * 6;
    g.fillStyle = `rgb(${shade},${shade},${shade + 3})`;
    g.beginPath();
    g.moveTo(cx, cx);
    g.arc(cx, cx, 1.96 * pxm, a0, a1);
    g.closePath();
    g.fill();
    // pillowing: lighter centre of each gore in the bump map
    const grad = gb.createRadialGradient(cx + Math.cos((a0 + a1) / 2) * 1.35 * pxm, cx + Math.sin((a0 + a1) / 2) * 1.35 * pxm, 0, cx + Math.cos((a0 + a1) / 2) * 1.35 * pxm, cx + Math.sin((a0 + a1) / 2) * 1.35 * pxm, 0.6 * pxm);
    grad.addColorStop(0, 'rgba(255,255,255,0.35)');
    grad.addColorStop(1, 'rgba(255,255,255,0)');
    gb.fillStyle = grad;
    gb.beginPath();
    gb.moveTo(cx, cx);
    gb.arc(cx, cx, 1.96 * pxm, a0, a1);
    gb.closePath();
    gb.fill();
  }
  // gore seams
  g.strokeStyle = 'rgba(40,40,42,0.8)';
  gb.strokeStyle = '#303030';
  g.lineWidth = gb.lineWidth = 3;
  for (let k = 0; k < gores; k++) {
    const a = (k / gores) * Math.PI * 2;
    for (const ctx2 of [g, gb]) {
      ctx2.beginPath();
      ctx2.moveTo(cx + Math.cos(a) * 0.85 * pxm, cx + Math.sin(a) * 0.85 * pxm);
      ctx2.lineTo(cx + Math.cos(a) * 1.95 * pxm, cx + Math.sin(a) * 1.95 * pxm);
      ctx2.stroke();
    }
  }
  // rings: stiffener at 1.2 m, outer edge band
  for (const [rr, w, col] of [[1.2, 10, '#6d6e70'], [1.93, 14, '#5b5c5e'], [0.87, 12, '#4a4a4c']]) {
    g.strokeStyle = col;
    g.lineWidth = w;
    g.beginPath();
    g.arc(cx, cx, rr * pxm, 0, Math.PI * 2);
    g.stroke();
    gb.strokeStyle = '#c0c0c0';
    gb.lineWidth = w * 0.6;
    gb.beginPath();
    gb.arc(cx, cx, rr * pxm, 0, Math.PI * 2);
    gb.stroke();
  }
  // bolt circles
  g.fillStyle = '#3a3a3c';
  for (const [rr, n] of [[1.93, 96], [1.2, 64], [0.9, 36]]) {
    for (let k = 0; k < n; k++) {
      const a = (k / n) * Math.PI * 2;
      g.beginPath();
      g.arc(cx + Math.cos(a) * rr * pxm, cx + Math.sin(a) * rr * pxm, 2.2, 0, Math.PI * 2);
      g.fill();
    }
  }
  const map = canvasTex(c);
  const bump = canvasTex(b, { srgb: false });
  return { map, bump };
}
